FROM node:lts-alpine AS build-stage

COPY . /app
WORKDIR /app

RUN set -xe \
    && apk add --no-cache yarn \
    && yarn install && yarn build

FROM nginx:1.19.3-alpine

RUN set -xe \
    && mkdir /app \
    && apk --no-cache add bash vim

COPY ./docker/app/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build-stage /app/dist /app

EXPOSE 80

CMD bash -c "nginx -g 'daemon off;'"
ENTRYPOINT []