version: '3.8'

services:
  frontend:
    image: registry.gitlab.com/zabbixmc/zabbixmc/app:latest
    command: ['nginx', '-g', 'daemon off;']
    volumes:
      - .env.local:/app/.env.local
    ports:
      - "8090:80"
